<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Condition="'$(OS)'=='Windows_NT'">
    <TargetFrameworks>net9.0;net8.0;net48</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(OS)'!='Windows_NT'">
    <TargetFrameworks>net9.0;net8.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSTest.TestFramework" Version="3.8.3" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.8.3" PrivateAssets="All" />
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Toolbox\CreateAndFake.csproj" />
    <ProjectReference Include="..\..\src\MSTest\CreateAndFake.MSTest.csproj" />
    <Using Include="CreateAndFake" />
    <Using Include="CreateAndFake.Fluent" />
    <Using Include="CreateAndFake.MSTest" />
  </ItemGroup>

</Project>
