name: Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testing:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    environment: staging
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.0.x
          8.0.x
    - name: Build & Test
      run: ./build/run.sh test
    
  coverage:
    runs-on: windows-2025
    environment: staging
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.0.x
          8.0.x
    - name: Build & Check Test Coverage
      shell: cmd
      run: ./build/run.cmd coverage
    - name: Upload Coverage
      uses: codecov/codecov-action@v4
      with:
        directory: ./artifacts/coverage
        token: ${{ secrets.CODECOV_TOKEN }}
